from flask import Flask, request, jsonify
import geopandas as gpd
from shapely.geometry import Point

# Get shape of municipalities and parishes
portugal_municipalities = gpd.read_file("concelhos.shp")

# Remove islands
portugal_municipalities = portugal_municipalities[
    portugal_municipalities.NAME_1 != "Azores"
]
portugal_municipalities = portugal_municipalities[
    portugal_municipalities.NAME_1 != "Madeira"
]

app = Flask(__name__)
app.register_error_handler(400, lambda: ("Bad request!", 400))


# Solve CORS issues
@app.after_request
def after_request(response):
    response.headers.add("Access-Control-Allow-Origin", "*")
    response.headers.add("Access-Control-Allow-Headers", "Content-Type,Authorization")
    response.headers.add("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE,OPTIONS")
    return response


@app.route("/ping", methods=["GET"])
def ping():
    return "pong"


@app.route("/get_location", methods=["GET"])
def get_municipality():
    lat = request.args.get("lat", type=float)
    lon = request.args.get("lon", type=float)
    user_point = Point(lon, lat)
    for index, row in portugal_municipalities.iterrows():
        polygon = row["geometry"]
        # Check if the point is inside the polygon
        if polygon.contains(user_point):
            # Return the index or other properties of the polygon
            return jsonify(
                {
                    "district": row.NAME_1,
                    "municipality": row.NAME_2,
                }
            )
    return jsonify(
        {
            "district": None,
            "municipality": None,
        }
    )


issue_by_municipality = {
    "MOITA": "Assistência em Saúde",
    "CASTRO VERDE": "Assistência em Saúde",
    "MAFRA": "Assistência em Saúde",
    "RESENDE": "Assistência em Saúde",
    "SANTARÉM": "Assistência em Saúde",
    "GONDOMAR": "Assistência em Saúde",
    "MEALHADA": "Assistência em Saúde",
    "CASTELO BRANCO": "Assistência em Saúde",
    "VILA NOVA DA BARQUINHA": "Assistência em Saúde",
    "VILA VELHA DE RÓDÃO": "Assistência em Saúde",
    "SABUGAL": "Assistência em Saúde",
    "TONDELA": "Assistência em Saúde",
    "ALENQUER": "Assistência em Saúde",
    "SINTRA": "Assistência em Saúde",
    "PAREDES": "Assistência em Saúde",
    "OLIVEIRA DE AZEMÉIS": "Assistência em Saúde",
    "OEIRAS": "Assistência em Saúde",
    "TOMAR": "Assistência em Saúde",
    "VILA NOVA DE FAMALICÃO": "Assistência em Saúde",
    "CASTRO DAIRE": "Assistência em Saúde",
    "TÁBUA": "Assistência em Saúde",
    "VILA DO CONDE": "Assistência em Saúde",
    "SANTO TIRSO": "Assistência em Saúde",
    "VILA FLOR": "Assistência e Prevenção a actividades humanas",
    "LEIRIA": "Assistência em Saúde",
    "PONTE DE LIMA": "Assistência em Saúde",
    "PAÇOS DE FERREIRA": "Assistência e Prevenção a actividades humanas",
    "CALDAS DA RAINHA": "Assistência em Saúde",
    "BARCELOS": "Assistência em Saúde",
    "PORTIMÃO": "Assistência em Saúde",
    "LAGOS": "Assistência em Saúde",
    "FORNOS DE ALGODRES": "Assistência em Saúde",
    "VAGOS": "Assistência em Saúde",
    "VALE DE CAMBRA": "Assistência em Saúde",
    "ALBERGARIA-A-VELHA": "Assistência em Saúde",
    "SÃO JOÃO DA MADEIRA": "Assistência em Saúde",
    "TAVIRA": "Assistência em Saúde",
    "GOLEGÃ": "Assistência em Saúde",
    "RIO MAIOR": "Assistência em Saúde",
    "ABRANTES": "Assistência e Prevenção a actividades humanas",
    "MAÇÃO": "Assistência e Prevenção a actividades humanas",
    "ALMEIDA": "Assistência em Saúde",
    "OLIVEIRA DO HOSPITAL": "Assistência em Saúde",
    "POMBAL": "Assistência em Saúde",
    "VALPAÇOS": "Assistência em Saúde",
    "LAMEGO": "Assistência em Saúde",
    "PENALVA DO CASTELO": "Assistência em Saúde",
    "GUARDA": "Assistência em Saúde",
    "ALCANENA": "Assistência em Saúde",
    "PENAMACOR": "Assistência em Saúde",
    "FERREIRA DO ZÊZERE": "Assistência e Prevenção a actividades humanas",
    "COVILHÃ": "Assistência em Saúde",
    "OURÉM": "Assistência em Saúde",
    "SÁTÃO": "Assistência em Saúde",
    "VILA NOVA DE PAIVA": "Assistência e Prevenção a actividades humanas",
    "VISEU": "Assistência e Prevenção a actividades humanas",
    "SILVES": "Assistência em Saúde",
    "CARTAXO": "Assistência em Saúde",
    "ALPIARÇA": "Assistência em Saúde",
    "VILA NOVA DE GAIA": "Assistência em Saúde",
    "MONCHIQUE": "Assistência em Saúde",
    "ODEMIRA": "Assistência em Saúde",
    "SARDOAL": "Assistência e Prevenção a actividades humanas",
    "LOUSADA": "Assistência em Saúde",
    "VALONGO": "Assistência em Saúde",
    "ALJEZUR": "Assistência em Saúde",
    "TORRES VEDRAS": "Assistência em Saúde",
    "OLEIROS": "Assistência em Saúde",
    "MAIA": "Assistência em Saúde",
    "PORTO DE MÓS": "Assistência em Saúde",
    "ALMEIRIM": "Assistência em Saúde",
    "AVEIRO": "Assistência em Saúde",
    "FARO": "Assistência e Prevenção a actividades humanas",
    "VILA REAL DE SANTO ANTÓNIO": "Assistência em Saúde",
    "CASCAIS": "Assistência em Saúde",
    "TORRES NOVAS": "Assistência em Saúde",
    "OLHÃO": "Assistência em Saúde",
    "BENAVENTE": "Assistência em Saúde",
    "BEJA": "Assistência em Saúde",
    "CASTRO MARIM": "Assistência em Saúde",
    "SOURE": "Assistência em Saúde",
    "VILA DO BISPO": "Assistência e Prevenção a actividades humanas",
    "VOUZELA": "Assistência em Saúde",
    "ENTRONCAMENTO": "Assistência em Saúde",
    "LAGOA": "Assistência em Saúde",
    "FUNDÃO": "Assistência em Saúde",
    "SEIA": "Assistência em Saúde",
    "NELAS": "Assistência e Prevenção a actividades humanas",
    "BOMBARRAL": "Assistência em Saúde",
    "CHAMUSCA": "Assistência e Prevenção a actividades humanas",
    "SALVATERRA DE MAGOS": "Assistência em Saúde",
    "ARGANIL": "Assistência em Saúde",
    "SESIMBRA": "Assistência em Saúde",
    "ALCÁCER DO SAL": "Assistência em Saúde",
    "IDANHA-A-NOVA": "Assistência em Saúde",
    "CAMINHA": "Assistência em Saúde",
    "AROUCA": "Assistência em Saúde",
    "VALENÇA": "Assistência em Saúde",
    "AMARANTE": "Assistência em Saúde",
    "PENAFIEL": "Assistência em Saúde",
    "PINHEL": "Assistência em Saúde",
    "COIMBRA": "Assistência e Prevenção a actividades humanas",
    "PENACOVA": "Assistência em Saúde",
    "CONDEIXA-A-NOVA": "Assistência em Saúde",
    "BORBA": "Assistência e Prevenção a actividades humanas",
    "CARREGAL DO SAL": "Assistência em Saúde",
    "LOURES": "Assistência em Saúde",
    "REGUENGOS DE MONSARAZ": "Assistência em Saúde",
    "PALMELA": "Assistência em Saúde",
    "OLIVEIRA DO BAIRRO": "Assistência em Saúde",
    "LOURINHÃ": "Assistência em Saúde",
    "ALBUFEIRA": "Assistência em Saúde",
    "LOULÉ": "Assistência em Saúde",
    "MELGAÇO": "Assistência em Saúde",
    "SEIXAL": "Assistência em Saúde",
    "MANTEIGAS": "Assistência em Saúde",
    "AMADORA": "Assistência em Saúde",
    "CINFÃES": "Assistência em Saúde",
    "MARCO DE CANAVESES": "Assistência em Saúde",
    "MONÇÃO": "Assistência em Saúde",
    "MARINHA GRANDE": "Assistência em Saúde",
    "FELGUEIRAS": "Assistência em Saúde",
    "FIGUEIRA DA FOZ": "Assistência em Saúde",
    "SÃO BRÁS DE ALPORTEL": "Assistência em Saúde",
    "CADAVAL": "Assistência em Saúde",
    "ARMAMAR": "Assistência em Saúde",
    "ARCOS DE VALDEVEZ": "Assistência em Saúde",
    "SÃO PEDRO DO SUL": "Assistência e Prevenção a actividades humanas",
    "MOURÃO": "Assistência em Saúde",
    "PORTO": "Assistência em Saúde",
    "PAREDES DE COURA": "Assistência em Saúde",
    "MÊDA": "Assistência em Saúde",
    "PEDRÓGÃO GRANDE": "Assistência em Saúde",
    "CONSTÂNCIA": "Assistência e Prevenção a actividades humanas",
    "VENDAS NOVAS": "Assistência em Saúde",
    "ÉVORA": "Assistência em Saúde",
    "ODIVELAS": "Assistência em Saúde",
    "PENICHE": "Assistência em Saúde",
    "SERTÃ": "Assistência em Saúde",
    "PENEDONO": "Assistência em Saúde",
    "CELORICO DA BEIRA": "Assistência em Saúde",
    "VILA FRANCA DE XIRA": "Assistência em Saúde",
    "ALFÂNDEGA DA FÉ": "Assistência e Prevenção a actividades humanas",
    "TORRE DE MONCORVO": "Assistência e Prevenção a actividades humanas",
    "ANADIA": "Assistência em Saúde",
    "MACEDO DE CAVALEIROS": "Assistência e Prevenção a actividades humanas",
    "PORTALEGRE": "Assistência em Saúde",
    "TABUAÇO": "Assistência e Prevenção a actividades humanas",
    "ESTREMOZ": "Assistência em Saúde",
    "ALCOCHETE": "Assistência em Saúde",
    "ALVAIÁZERE": "Assistência em Saúde",
    "ÁGUEDA": "Assistência em Saúde",
    "BRAGANÇA": "Assistência em Saúde",
    "PONTE DA BARCA": "Assistência em Saúde",
    "BARREIRO": "Assistência em Saúde",
    "ALMADA": "Assistência em Saúde",
    "PÓVOA DE LANHOSO": "Assistência em Saúde",
    "VILA POUCA DE AGUIAR": "Assistência em Saúde",
    "SANTA MARIA DA FEIRA": "Assistência em Saúde",
    "BRAGA": "Assistência em Saúde",
    "SETÚBAL": "Assistência e Prevenção a actividades humanas",
    "LISBOA": "Assistência em Saúde",
    "MIRANDA DO CORVO": "Assistência e Prevenção a actividades humanas",
    "ÍLHAVO": "Assistência em Saúde",
    "CUBA": "Assistência em Saúde",
    "FIGUEIRA DE CASTELO RODRIGO": "Assistência em Saúde",
    "ELVAS": "Assistência em Saúde",
    "FAFE": "Assistência em Saúde",
    "GUIMARÃES": "Assistência em Saúde",
    "MATOSINHOS": "Assistência em Saúde",
    "ANSIÃO": "Assistência em Saúde",
    "MONTALEGRE": "Incêndios Rurais",
    "SOUSEL": "Assistência e Prevenção a actividades humanas",
    "PENELA": "Assistência e Prevenção a actividades humanas",
    "SANTIAGO DO CACÉM": "Assistência em Saúde",
    "AMARES": "Assistência em Saúde",
    "MOIMENTA DA BEIRA": "Assistência em Saúde",
    "CANTANHEDE": "Assistência em Saúde",
    "CHAVES": "Assistência em Saúde",
    "CABECEIRAS DE BASTO": "Assistência em Saúde",
    "VILA NOVA DE POIARES": "Assistência em Saúde",
    "BELMONTE": "Assistência em Saúde",
    "TROFA": "Assistência em Saúde",
    "SINES": "Assistência em Saúde",
    "CORUCHE": "Assistência e Prevenção a actividades humanas",
    "SÃO JOÃO DA PESQUEIRA": "Assistência em Saúde",
    "CASTELO DE VIDE": "Assistência e Prevenção a actividades humanas",
    "VILA VERDE": "Assistência em Saúde",
    "MONTEMOR-O-NOVO": "Assistência em Saúde",
    "FREIXO DE ESPADA À CINTA": "Assistência e Prevenção a actividades humanas",
    "NISA": "Assistência e Prevenção a actividades humanas",
    "LOUSÃ": "Assistência em Saúde",
    "VILA REAL": "Assistência em Saúde",
    "PÓVOA DE VARZIM": "Assistência em Saúde",
    "ALCOBAÇA": "Assistência em Saúde",
    "ESTARREJA": "Assistência em Saúde",
    "VIEIRA DO MINHO": "Assistência em Saúde",
    "SEVER DO VOUGA": "Assistência em Saúde",
    "OVAR": "Assistência em Saúde",
    "GOUVEIA": "Assistência em Saúde",
    "ALVITO": "Assistência em Saúde",
    "MOGADOURO": "Assistência e Prevenção a actividades humanas",
    "TRANCOSO": "Assistência em Saúde",
    "VIANA DO CASTELO": "Assistência e Prevenção a actividades humanas",
    "ALJUSTREL": "Assistência em Saúde",
    "MIRANDA DO DOURO": "Assistência e Prevenção a actividades humanas",
    "VIZELA": "Assistência em Saúde",
    "AVIS": "Assistência e Prevenção a actividades humanas",
    "BAIÃO": "Assistência e Prevenção a actividades humanas",
    "MÉRTOLA": "Assistência e Prevenção a actividades humanas",
    "ÓBIDOS": "Assistência em Saúde",
    "MONTIJO": "Assistência em Saúde",
    "BATALHA": "Assistência em Saúde",
    "AZAMBUJA": "Assistência em Saúde",
    "ARRAIOLOS": "Assistência em Saúde",
    "GRÂNDOLA": "Assistência em Saúde",
    "SANTA MARTA DE PENAGUIÃO": "Assistência em Saúde",
    "CELORICO DE BASTO": "Assistência em Saúde",
    "RIBEIRA DE PENA": "Assistência em Saúde",
    "PESO DA RÉGUA": "Assistência em Saúde",
    "MONDIM DE BASTO": "Assistência e Prevenção a actividades humanas",
    "MONTEMOR-O-VELHO": "Assistência em Saúde",
    "MURÇA": "Assistência em Saúde",
    "CASTELO DE PAIVA": "Assistência em Saúde",
    "MURTOSA": "Assistência em Saúde",
    "MIRA": "Assistência em Saúde",
    "PAMPILHOSA DA SERRA": "Assistência em Saúde",
    "VIDIGUEIRA": "Assistência em Saúde",
    "VILA NOVA DE FOZ CÔA": "Assistência em Saúde",
    "ESPINHO": "Assistência em Saúde",
    "SERPA": "Assistência em Saúde",
    "MORTÁGUA": "Assistência em Saúde",
    "FIGUEIRÓ DOS VINHOS": "Assistência em Saúde",
    "PONTE DE SOR": "Assistência e Prevenção a actividades humanas",
    "PORTEL": "Assistência e Prevenção a actividades humanas",
    "CAMPO MAIOR": "Assistência em Saúde",
    "MIRANDELA": "Assistência e Prevenção a actividades humanas",
    "FERREIRA DO ALENTEJO": "Assistência em Saúde",
    "ESPOSENDE": "Assistência em Saúde",
    "ARRUDA DOS VINHOS": "Assistência em Saúde",
    "TAROUCA": "Assistência em Saúde",
    "MONFORTE": "Assistência e Prevenção a actividades humanas",
    "SOBRAL DE MONTE AGRAÇO": "Assistência em Saúde",
    "SABROSA": "Assistência em Saúde",
    "OLIVEIRA DE FRADES": "Assistência em Saúde",
    "PROENÇA-A-NOVA": "Assistência em Saúde",
    "MOURA": "Assistência em Saúde",
    "SANTA COMBA DÃO": "Assistência em Saúde",
    "ALIJÓ": "Assistência em Saúde",
    "ALMODÔVAR": "Assistência e Prevenção a actividades humanas",
    "BOTICAS": "Incêndios Rurais",
    "VILA DE REI": "Assistência em Saúde",
    "ALTER DO CHÃO": "Assistência e Prevenção a actividades humanas",
    "SERNANCELHE": "Assistência e Prevenção a actividades humanas",
    "MANGUALDE": "Assistência em Saúde",
    "REDONDO": "Assistência em Saúde",
    "VILA NOVA DE CERVEIRA": "Assistência em Saúde",
    "ARRONCHES": "Assistência em Saúde",
    "OURIQUE": "Assistência em Saúde",
    "TERRAS DE BOURO": "Assistência em Saúde",
    "NAZARÉ": "Assistência em Saúde",
    "VINHAIS": "Assistência e Prevenção a actividades humanas",
    "CARRAZEDA DE ANSIÃES": "Assistência e Prevenção a actividades humanas",
    "MESÃO FRIO": "Assistência em Saúde",
    "BARRANCOS": "Assistência e Prevenção a actividades humanas",
    "VIANA DO ALENTEJO": "Assistência em Saúde",
    "CASTANHEIRA DE PÊRA": "Assistência em Saúde",
    "ALCOUTIM": "Assistência em Saúde",
    "VILA VIÇOSA": "Assistência em Saúde",
    "GAVIÃO": "Assistência e Prevenção a actividades humanas",
    "CRATO": "Assistência e Prevenção a actividades humanas",
    "VIMIOSO": "Assistência e Prevenção a actividades humanas",
    "MORA": "Assistência em Saúde",
    "GÓIS": "Assistência e Prevenção a actividades humanas",
    "FRONTEIRA": "Assistência e Prevenção a actividades humanas",
    "AGUIAR DA BEIRA": "Assistência em Saúde",
    "MARVÃO": "Assistência e Prevenção a actividades humanas",
    "ALANDROAL": "Assistência em Saúde",
}
hh_by_cat = {
    "Assistência em Saúde": 121.2,
    "Assistência e Prevenção a actividades humanas": 105.94,
    "Acidentes": 33.95,
    "Incêndios Rurais": 141.93,
    "Intervenção em conflitos legais": 15.65,
    "Comprometimento total ou parcial de segurança, serviços ou estruturas": 59.48,
    "Incêndios Urbanos ou em Área Urbanizável": 47.05,
    "Incêndios em Detritos": 10.33,
    "Incêndios em Transportes": 16.54,
    "Incêndios em Equipamento e Produtos": 8.07,
    "Operações": 19.28,
    "Acidentes industriais e tecnológicos": 509.76,
    "Fenómenos Naturais": 20.13,
}


@app.route("/predict", methods=["GET"])
def get_tags_data():
    municipality = request.args.get("municipality", type=str)
    issue = request.args.get("issue", type=str)
    risk_issue = issue_by_municipality[municipality.upper()]
    hh = hh_by_cat[issue]

    return jsonify({"risk_issue": risk_issue, "hh": hh})


if __name__ == "__main__":
    app.run(host="0.0.0.0")
